-- Pure AXON UI layout manifest (from captured script, with gameplay callbacks removed).
-- This returns declarative control definitions; it does not render a menu by itself.
local KEY_OPTIONS={"Right Mouse","Left Mouse","Q","E","C","F","V","X","Z","Shift","Always On"}
local VM_MATERIALS={"Neon","ForceField","Glass","SmoothPlastic","Plastic","Metal","DiamondPlate","Foil","Marble","Glacier","Ice","Wood"}
local hsValues={"(hitsounds.lua not loaded)"}
return {
  {tab="Aimbot", side="Left", section="Aimbot", kind="Toggle", src=2335, id="aim_enabled", title="Enable Aimbot", desc="Locks the camera onto the best enemy in your FOV while the aim key is held. The game shoots along the camera, so a normal shot lands.", default=false},
  {tab="Aimbot", side="Left", section="Aimbot", kind="Dropdown", src=2336, id="aim_key", title="Aim Key", default=1, values=KEY_OPTIONS},
  {tab="Aimbot", side="Left", section="Aimbot", kind="Slider", src=2337, id="aim_fov", title="FOV (px radius)", default=250, min=20, max=1200, rounding=0},
  {tab="Aimbot", side="Left", section="Aimbot", kind="Slider", src=2338, id="aim_smooth", title="Smoothing (0 = instant)", default=0.2, min=0, max=1, rounding=2},
  {tab="Aimbot", side="Left", section="Aimbot", kind="Dropdown", src=2339, id="aim_part", title="Target Part", desc="'Shared' uses the Targeting tab.", default=1, values={ "Shared", "Head", "Torso", "Pelvis", "Root", "Nearest" }},
  {tab="Aimbot", side="Right", section="Behaviour", kind="Toggle", src=2340, id="aim_autofire", title="Auto Fire While Locked", desc="Fires for you when a target is locked.", default=false},
  {tab="Aimbot", side="Right", section="Behaviour", kind="Slider", src=2341, id="aim_fire_rate", title="Fire Rate (ms)", default=80, min=0, max=600, rounding=0},
  {tab="Aimbot", side="Right", section="Behaviour", kind="Toggle", src=2342, id="aim_target_line", title="Target Line", default=false},
  {tab="Aimbot", side="Right", section="Hit Sounds", kind="Toggle", src=2346, id="hit_sound_enabled", title="Hit Sound", desc="Plays your chosen sound whenever aimbot / silent / rage / a normal shot DAMAGES an enemy.", default=false},
  {tab="Aimbot", side="Right", section="Hit Sounds", kind="Dropdown", src=2347, id="hit_sound_name", title="Sound", desc="Pick the sound that plays on a hit.", default=1, values=hsValues},
  {tab="Aimbot", side="Right", section="Hit Sounds", kind="Slider", src=2348, id="hit_sound_volume", title="Volume %", default=100, min=0, max=300, rounding=0},
  {tab="Aimbot", side="Right", section="Hit Sounds", kind="Button", src=2349, title="Test Sound"},
  {tab="Silent", side="Left", section="Silent Aim", kind="Toggle", src=2358, id="silent_enabled", title="Enable Silent Aim", desc="Lands hits on the best enemy with NO camera movement - works even when you're not looking at them. Hold the key and fire.", default=false},
  {tab="Silent", side="Left", section="Silent Aim", kind="Dropdown", src=2359, id="silent_key", title="Activation Key", default=#KEY_OPTIONS, values=KEY_OPTIONS},
  {tab="Silent", side="Left", section="Silent Aim", kind="Slider", src=2360, id="silent_fov", title="FOV (px radius)", default=400, min=20, max=4000, rounding=0},
  {tab="Silent", side="Left", section="Silent Aim", kind="Slider", src=2361, id="silent_hitchance", title="Hit Chance %", desc="Under 100 randomly lets some shots stay real.", default=100, min=0, max=100, rounding=0},
  {tab="Silent", side="Left", section="Silent Aim", kind="Toggle", src=2362, id="silent_force_headshot", title="Force Headshot", default=true},
  {tab="Silent", side="Right", section="Silent Behaviour", kind="Toggle", src=2363, id="silent_target_line", title="Target Line", default=false},
  {tab="Silent", side="Right", section="Silent Behaviour", kind="Paragraph", src=2364, id="silent_note", title="How it works", content="Each shot the firearm sends the server a Discharge with the bullet's origin + aim angle, and the SERVER re-simulates it to decide the hit. We rewrite only the angle to point at the target - so the server sees a normal shot aimed at the enemy while your camera never moves. No look required, no recoil to fight."},
  {tab="Rage", side="Left", section="Ragebot", kind="Toggle", src=2373, id="rage_enabled", title="Enable Ragebot", desc="Always-on, no-key silent aim: redirects EVERY shot to the best enemy on screen with no camera movement.", default=false},
  {tab="Rage", side="Left", section="Ragebot", kind="Slider", src=2374, id="rage_fov", title="FOV (px radius)", desc="9999 = whole screen.", default=9999, min=50, max=9999, rounding=0},
  {tab="Rage", side="Left", section="Ragebot", kind="Toggle", src=2375, id="rage_force_headshot", title="Force Headshot", default=true},
  {tab="Rage", side="Left", section="Ragebot", kind="Toggle", src=2376, id="rage_ignore_walls", title="Ignore Walls (risky)", default=false},
  {tab="Rage", side="Left", section="Ragebot", kind="Slider", src=2377, id="rage_hitchance", title="Hit Chance %", default=100, min=0, max=100, rounding=0},
  {tab="Rage", side="Right", section="Auto Fire & Ballistics", kind="Toggle", src=2378, id="rage_autofire", title="Auto Fire", desc="Pulls the trigger whenever a target exists.", default=false},
  {tab="Rage", side="Right", section="Auto Fire & Ballistics", kind="Slider", src=2379, id="rage_fire_rate", title="Fire Rate (ms)", default=120, min=0, max=600, rounding=0},
  {tab="Rage", side="Right", section="Auto Fire & Ballistics", kind="Toggle", src=2380, id="rage_dropcomp", title="Drop Compensation", desc="Re-aim pitch for bullet drop (uses the payload's projectile velocity).", default=true},
  {tab="Rage", side="Right", section="Auto Fire & Ballistics", kind="Slider", src=2381, id="rage_gravity", title="Gravity", default=32, min=1, max=200, rounding=0},
  {tab="Rage", side="Right", section="Auto Fire & Ballistics", kind="Toggle", src=2382, id="rage_target_line", title="Target Line", default=false},
  {tab="Trigger", side="Left", section="Triggerbot", kind="Toggle", src=2390, id="trig_enabled", title="Enable Triggerbot", desc="Auto-fires the moment your crosshair is over an enemy.", default=false},
  {tab="Trigger", side="Left", section="Triggerbot", kind="Dropdown", src=2391, id="trig_key", title="Activation Key", default=#KEY_OPTIONS, values=KEY_OPTIONS},
  {tab="Trigger", side="Left", section="Triggerbot", kind="Slider", src=2392, id="trig_delay", title="Reaction Delay (ms)", default=30, min=0, max=500, rounding=0},
  {tab="Target", side="Left", section="Target Part & Priority", kind="Dropdown", src=2401, id="tgt_part", title="Body Part", default=1, values={ "Head", "Torso", "Pelvis", "Root", "Nearest" }},
  {tab="Target", side="Left", section="Target Part & Priority", kind="Dropdown", src=2402, id="tgt_priority", title="Target Priority", default=1, values={ "Crosshair", "Distance", "Lowest HP" }},
  {tab="Target", side="Left", section="Target Part & Priority", kind="Toggle", src=2403, id="tgt_sticky", title="Sticky Target", desc="Holds the same target until it dies or leaves the FOV.", default=false},
  {tab="Target", side="Left", section="Target Part & Priority", kind="Slider", src=2404, id="tgt_max_dist", title="Max Distance (studs)", default=2000, min=20, max=6000, rounding=0},
  {tab="Target", side="Right", section="Filters & Prediction", kind="Toggle", src=2405, id="tgt_team_check", title="Squad Check", desc="Only target enemies on a DIFFERENT squad than you (your squad-mates are skipped). Turn off for free-for-all to target everyone but yourself.", default=true},
  {tab="Target", side="Right", section="Filters & Prediction", kind="Toggle", src=2406, id="tgt_wall_check", title="Visible Check", desc="Only target enemies your bullet could actually reach. Rays from your head and only SOLID walls block it.", default=true},
  {tab="Target", side="Right", section="Filters & Prediction", kind="Toggle", src=2407, id="tgt_penetrate", title="Shoot Through Glass/Bodies", desc="Treat glass, foliage, other players' bodies and non-collidable 'trash' as see-through in the Visible Check - the things a bullet really passes through.", default=true},
  {tab="Target", side="Right", section="Filters & Prediction", kind="Toggle", src=2408, id="tgt_predict", title="Projectile Prediction", desc="Leads moving targets. Set bullet speed (0 = hitscan).", default=false},
  {tab="Target", side="Right", section="Filters & Prediction", kind="Slider", src=2409, id="tgt_bulletspeed", title="Bullet Speed (studs/s)", default=0, min=0, max=9000, rounding=0},
  {tab="Target", side="Right", section="Filters & Prediction", kind="Slider", src=2410, id="tgt_predict_strength", title="Prediction Strength", default=1, min=0, max=2, rounding=2},
  {tab="GunMods", side="Left", section="Firearm", kind="Toggle", src=2420, id="gun_norecoil", title="No Recoil", default=false},
  {tab="GunMods", side="Left", section="Firearm", kind="Toggle", src=2427, id="gun_nospread", title="No Spread", default=false},
  {tab="GunMods", side="Left", section="Firearm", kind="Toggle", src=2432, id="gun_firerate_on", title="Custom Fire Rate", default=false},
  {tab="GunMods", side="Left", section="Firearm", kind="Slider", src=2435, id="gun_firerate", title="Fire Rate (RPM)", default=900, min=60, max=3000, rounding=0},
  {tab="GunMods", side="Left", section="Firearm", kind="Toggle", src=2439, id="gun_firemode_on", title="Override Fire Mode", default=false},
  {tab="GunMods", side="Left", section="Firearm", kind="Dropdown", src=2446, id="gun_firemode", title="Fire Mode", default=1, values={ "Automatic", "Semi-Automatic", "Burst" }},
  {tab="GunMods", side="Right", section="Ammo & Notes", kind="Toggle", src=2453, id="gun_highammo", title="High Mag Capacity", default=false},
  {tab="GunMods", side="Right", section="Ammo & Notes", kind="Slider", src=2456, id="gun_ammo", title="Mag Ammo", default=200, min=1, max=999, rounding=0},
  {tab="GunMods", side="Right", section="Ammo & Notes", kind="Toggle", src=2459, id="gun_highmags", title="High Reserve Mags", default=false},
  {tab="GunMods", side="Right", section="Ammo & Notes", kind="Slider", src=2462, id="gun_mags", title="Reserve Mags", default=50, min=1, max=999, rounding=0},
  {tab="GunMods", side="Right", section="Ammo & Notes", kind="Paragraph", src=2465, id="gun_note", title="Client-side tuning", content="These edit the weapon ModuleScripts your client reads when it fires. Effects apply to your gun; restore on toggle-off or Unload. No getgc heap scans, so they will not freeze the game."},
  {tab="GunMods", side="Left", section="Bullet Tracer", kind="Toggle", src=2468, id="tracer_enabled", title="Gun Tracer", desc="Draws a beam along every bullet you fire (follows silent aim if on).", default=false},
  {tab="GunMods", side="Left", section="Bullet Tracer", kind="Colorpicker", src=2469, id="tracer_color", title="Color", default=Color3.fromRGB(255, 200, 40)},
  {tab="GunMods", side="Left", section="Bullet Tracer", kind="Toggle", src=2470, id="tracer_rainbow", title="Rainbow", desc="Cycle the tracer color (overrides Color).", default=false},
  {tab="GunMods", side="Left", section="Bullet Tracer", kind="Slider", src=2471, id="tracer_rainbow_speed", title="Rainbow Speed", default=2, min=1, max=20, rounding=0},
  {tab="GunMods", side="Left", section="Bullet Tracer", kind="Slider", src=2472, id="tracer_width", title="Width", default=0.12, min=0.02, max=1, rounding=2},
  {tab="GunMods", side="Left", section="Bullet Tracer", kind="Slider", src=2473, id="tracer_transparency", title="Transparency", default=0, min=0, max=1, rounding=2},
  {tab="GunMods", side="Left", section="Bullet Tracer", kind="Toggle", src=2474, id="tracer_glow", title="Glow", desc="Neon-style light emission.", default=true},
  {tab="GunMods", side="Left", section="Bullet Tracer", kind="Slider", src=2475, id="tracer_brightness", title="Glow Brightness", default=3, min=0, max=10, rounding=1},
  {tab="GunMods", side="Left", section="Bullet Tracer", kind="Slider", src=2476, id="tracer_duration", title="Lifetime (s)", desc="How long each tracer stays before fading.", default=0.18, min=0.05, max=2, rounding=2},
  {tab="GunMods", side="Left", section="Bullet Tracer", kind="Slider", src=2477, id="tracer_range", title="Max Range (studs)", default=1000, min=100, max=5000, rounding=0},
  {tab="GunMods", side="Right", section="Reload", kind="Toggle", src=2480, id="reload_instant", title="Instant Reload", desc="Tops your mag up the instant it runs low - no animation, no delay. Shots are client-authoritative so the server accepts them.", default=false},
  {tab="GunMods", side="Right", section="Reload", kind="Slider", src=2481, id="reload_instant_at", title="Refill At (% of mag)", desc="Refill when the mag drops to this %. 0 = only when fully empty.", default=0, min=0, max=90, rounding=0},
  {tab="GunMods", side="Right", section="Reload", kind="Toggle", src=2482, id="reload_auto", title="Auto Reload", desc="Auto-presses reload (real animation) the moment your mag empties. Ignored if Instant Reload is on.", default=false},
  {tab="GunMods", side="Right", section="Reload", kind="Paragraph", src=2483, id="reload_note", title="Note", content="Instant Reload effectively gives infinite ammo with zero downtime. Auto Reload is the legit-looking option (plays the reload animation)."},
  {tab="ESP", side="Left", section="ESP", kind="Toggle", src=2492, id="esp_enabled", title="Enable ESP", default=false},
  {tab="ESP", side="Left", section="ESP", kind="Toggle", src=2493, id="esp_box", title="Boxes", default=true},
  {tab="ESP", side="Left", section="ESP", kind="Toggle", src=2494, id="esp_name", title="Names", default=true},
  {tab="ESP", side="Left", section="ESP", kind="Toggle", src=2495, id="esp_distance", title="Distance", default=true},
  {tab="ESP", side="Left", section="ESP", kind="Toggle", src=2496, id="esp_health", title="Health Bar", default=true},
  {tab="ESP", side="Left", section="ESP", kind="Toggle", src=2497, id="esp_skeleton", title="Skeleton", default=false},
  {tab="ESP", side="Left", section="ESP", kind="Toggle", src=2498, id="esp_headdot", title="Head Dot", default=false},
  {tab="ESP", side="Left", section="ESP", kind="Toggle", src=2499, id="esp_tracer", title="Tracers", default=false},
  {tab="ESP", side="Left", section="ESP", kind="Toggle", src=2500, id="esp_team", title="Show Allies Too", default=false},
  {tab="ESP", side="Left", section="ESP", kind="Slider", src=2501, id="esp_max_dist", title="Max Distance", default=2000, min=50, max=6000, rounding=0},
  {tab="ESP", side="Right", section="Colors & Extras", kind="Dropdown", src=2502, id="esp_tracer_origin", title="Tracer Origin", default=1, values={ "Bottom", "Center", "Top" }},
  {tab="ESP", side="Right", section="Colors & Extras", kind="Colorpicker", src=2503, id="esp_enemy_color", title="Enemy Color", default=Color3.fromRGB(255, 70, 70)},
  {tab="ESP", side="Right", section="Colors & Extras", kind="Colorpicker", src=2504, id="esp_ally_color", title="Ally Color", default=Color3.fromRGB(80, 170, 255)},
  {tab="ESP", side="Right", section="Colors & Extras", kind="Colorpicker", src=2505, id="esp_skeleton_color", title="Skeleton Color", default=Color3.fromRGB(255, 255, 255)},
  {tab="ESP", side="Right", section="Colors & Extras", kind="Colorpicker", src=2506, id="esp_tracer_color", title="Tracer Color", default=Color3.fromRGB(255, 255, 0)},
  {tab="ESP", side="Right", section="Colors & Extras", kind="Toggle", src=2507, id="vis_fov_circle", title="Show Aim FOV Circle", default=true},
  {tab="ESP", side="Right", section="Colors & Extras", kind="Colorpicker", src=2508, id="vis_fov_color", title="FOV Circle Color", default=Color3.fromRGB(255, 255, 255)},
  {tab="ESP", side="Right", section="Colors & Extras", kind="Colorpicker", src=2509, id="vis_target_line_color", title="Target Line Color", default=Color3.fromRGB(255, 255, 0)},
  {tab="ESP", side="Right", section="Colors & Extras", kind="Dropdown", src=2510, id="target_line_origin", title="Target Line Origin", default=1, values={ "Bottom", "Center", "Top", "Mouse" }},
  {tab="Chams", side="Left", section="Chams", kind="Toggle", src=2519, id="chams_enabled", title="Enable Chams", default=false},
  {tab="Chams", side="Left", section="Chams", kind="Toggle", src=2520, id="chams_xray", title="See Through Walls", default=true},
  {tab="Chams", side="Left", section="Chams", kind="Toggle", src=2521, id="chams_team", title="Show Allies Too", default=false},
  {tab="Chams", side="Left", section="Chams", kind="Slider", src=2522, id="chams_fill_transparency", title="Fill Transparency", default=0.5, min=0, max=1, rounding=2},
  {tab="Chams", side="Left", section="Chams", kind="Slider", src=2523, id="chams_outline_transparency", title="Outline Transparency", default=0, min=0, max=1, rounding=2},
  {tab="Chams", side="Right", section="Colors", kind="Colorpicker", src=2524, id="chams_enemy_fill", title="Enemy Fill", default=Color3.fromRGB(255, 60, 60)},
  {tab="Chams", side="Right", section="Colors", kind="Colorpicker", src=2525, id="chams_ally_fill", title="Ally Fill", default=Color3.fromRGB(60, 140, 255)},
  {tab="Chams", side="Right", section="Colors", kind="Colorpicker", src=2526, id="chams_outline", title="Outline", default=Color3.fromRGB(255, 255, 255)},
  {tab="World", side="Left", section="Lighting", kind="Toggle", src=2536, id="world_fullbright", title="Fullbright", default=false},
  {tab="World", side="Left", section="Lighting", kind="Slider", src=2537, id="world_brightness", title="Brightness", default=3, min=1, max=10, rounding=1},
  {tab="World", side="Left", section="Lighting", kind="Toggle", src=2538, id="world_nofog", title="No Fog", default=false},
  {tab="World", side="Left", section="Lighting", kind="Toggle", src=2539, id="world_fog_on", title="Custom Fog", default=false},
  {tab="World", side="Left", section="Lighting", kind="Slider", src=2540, id="world_fog_start", title="Fog Start", default=0, min=0, max=2000, rounding=0},
  {tab="World", side="Left", section="Lighting", kind="Slider", src=2541, id="world_fog_end", title="Fog End", default=1000, min=10, max=5000, rounding=0},
  {tab="World", side="Left", section="Lighting", kind="Toggle", src=2542, id="world_noatmosphere", title="No Atmosphere", default=false},
  {tab="World", side="Left", section="Lighting", kind="Toggle", src=2543, id="world_clock_on", title="Force Time Of Day", default=false},
  {tab="World", side="Left", section="Lighting", kind="Slider", src=2544, id="world_clock", title="Clock Time", default=14, min=0, max=24, rounding=1},
  {tab="World", side="Right", section="Modulation", kind="Toggle", src=2546, id="world_cc_on", title="Color Correction", desc="Saturation / contrast / brightness / tint over the whole screen.", default=false},
  {tab="World", side="Right", section="Modulation", kind="Slider", src=2547, id="world_saturation", title="Saturation", default=0, min=-1, max=3, rounding=2},
  {tab="World", side="Right", section="Modulation", kind="Slider", src=2548, id="world_contrast", title="Contrast", default=0, min=-1, max=1, rounding=2},
  {tab="World", side="Right", section="Modulation", kind="Slider", src=2549, id="world_cc_brightness", title="CC Brightness", default=0, min=-1, max=1, rounding=2},
  {tab="World", side="Right", section="Modulation", kind="Colorpicker", src=2550, id="world_tint", title="Tint Color", default=Color3.fromRGB(255, 255, 255)},
  {tab="World", side="Right", section="Modulation", kind="Toggle", src=2551, id="world_color_on", title="Ambient / Fog Tint", desc="Recolor world ambient, fog and sky shift.", default=false},
  {tab="World", side="Right", section="Modulation", kind="Colorpicker", src=2552, id="world_ambient", title="Ambient", default=Color3.fromRGB(120, 120, 120)},
  {tab="World", side="Right", section="Modulation", kind="Colorpicker", src=2553, id="world_outdoor", title="Outdoor Ambient", default=Color3.fromRGB(120, 120, 120)},
  {tab="World", side="Right", section="Modulation", kind="Colorpicker", src=2554, id="world_fogcolor", title="Fog Color", default=Color3.fromRGB(150, 150, 150)},
  {tab="World", side="Right", section="Modulation", kind="Colorpicker", src=2555, id="world_colorshift", title="Sky Color Shift", default=Color3.fromRGB(0, 0, 0)},
  {tab="Crosshair", side="Left", section="Custom Crosshair", kind="Toggle", src=2564, id="cross_enabled", title="Enable Crosshair", default=false},
  {tab="Crosshair", side="Left", section="Custom Crosshair", kind="Slider", src=2565, id="cross_size", title="Line Length", default=10, min=0, max=40, rounding=0},
  {tab="Crosshair", side="Left", section="Custom Crosshair", kind="Slider", src=2566, id="cross_gap", title="Center Gap", default=4, min=0, max=30, rounding=0},
  {tab="Crosshair", side="Left", section="Custom Crosshair", kind="Slider", src=2567, id="cross_thickness", title="Thickness", default=2, min=1, max=8, rounding=0},
  {tab="Crosshair", side="Left", section="Custom Crosshair", kind="Toggle", src=2568, id="cross_dot", title="Center Dot", default=false},
  {tab="Crosshair", side="Left", section="Custom Crosshair", kind="Slider", src=2569, id="cross_dot_size", title="Dot Size", default=2, min=1, max=10, rounding=0},
  {tab="Crosshair", side="Right", section="Animation & Style", kind="Toggle", src=2570, id="cross_tstyle", title="T Style (no top line)", default=false},
  {tab="Crosshair", side="Right", section="Animation & Style", kind="Slider", src=2571, id="cross_rotation", title="Static Tilt", default=0, min=0, max=360, rounding=0},
  {tab="Crosshair", side="Right", section="Animation & Style", kind="Toggle", src=2572, id="cross_spin", title="Spin", default=false},
  {tab="Crosshair", side="Right", section="Animation & Style", kind="Slider", src=2573, id="cross_spin_speed", title="Spin Speed", default=3, min=1, max=20, rounding=0},
  {tab="Crosshair", side="Right", section="Animation & Style", kind="Toggle", src=2574, id="cross_chroma", title="Chroma Color", default=false},
  {tab="Crosshair", side="Right", section="Animation & Style", kind="Slider", src=2575, id="cross_chroma_speed", title="Chroma Speed", default=1, min=1, max=10, rounding=0},
  {tab="Crosshair", side="Right", section="Animation & Style", kind="Colorpicker", src=2576, id="cross_color", title="Color", default=Color3.fromRGB(0, 255, 140)},
  {tab="Camera", side="Left", section="Third Person", kind="Toggle", src=2584, id="cam_thirdperson", title="Third Person", desc="Off = default first person. Drives the game's own camera, so it looks native - and unlocks maps that hard-force first person.", default=false},
  {tab="Camera", side="Left", section="Third Person", kind="Slider", src=2585, id="cam_tp_distance", title="Distance", default=8, min=1, max=25, rounding=0},
  {tab="Viewmodel", side="Left", section="Gun", kind="Toggle", src=2595, id="vm_gun_enabled", title="Enable Gun", desc="Re-material / recolor the held weapon.", default=false},
  {tab="Viewmodel", side="Left", section="Gun", kind="Dropdown", src=2596, id="vm_gun_material", title="Material", default=1, values=VM_MATERIALS},
  {tab="Viewmodel", side="Left", section="Gun", kind="Colorpicker", src=2597, id="vm_gun_color", title="Color", default=Color3.fromRGB(120, 200, 255)},
  {tab="Viewmodel", side="Left", section="Gun", kind="Toggle", src=2598, id="vm_gun_rainbow", title="Rainbow", desc="Cycle the color (overrides Color).", default=false},
  {tab="Viewmodel", side="Left", section="Gun", kind="Slider", src=2599, id="vm_gun_speed", title="Rainbow Speed", default=3, min=1, max=20, rounding=0},
  {tab="Viewmodel", side="Right", section="Arms / Hands", kind="Toggle", src=2601, id="vm_arm_enabled", title="Enable Arms", desc="Re-material / recolor your first-person arms and hands.", default=false},
  {tab="Viewmodel", side="Right", section="Arms / Hands", kind="Dropdown", src=2602, id="vm_arm_material", title="Material", default=1, values=VM_MATERIALS},
  {tab="Viewmodel", side="Right", section="Arms / Hands", kind="Colorpicker", src=2603, id="vm_arm_color", title="Color", default=Color3.fromRGB(255, 170, 120)},
  {tab="Viewmodel", side="Right", section="Arms / Hands", kind="Toggle", src=2604, id="vm_arm_rainbow", title="Rainbow", desc="Cycle the color (overrides Color).", default=false},
  {tab="Viewmodel", side="Right", section="Arms / Hands", kind="Slider", src=2605, id="vm_arm_speed", title="Rainbow Speed", default=3, min=1, max=20, rounding=0},
  {tab="Movement", side="Left", section="Ground Speed", kind="Toggle", src=2616, id="mv_walkspeed", title="Walk Speed", desc="Raises the movement controller's own velocity target so you move faster (ground/collision-checked, NOT a teleport). Crouch + prone scale too.", default=false},
  {tab="Movement", side="Left", section="Ground Speed", kind="Slider", src=2617, id="mv_walkspeed_mult", title="Speed Multiplier", desc="Multiplies your normal move speed. 1 = default, 2 = double.", default=2, min=1, max=6, rounding=1},
  {tab="Movement", side="Left", section="Ground Speed", kind="Toggle", src=2618, id="mv_air_momentum", title="Keep Velocity In Air", desc="Jumping no longer bleeds off your Walk Speed - the air (Falling) stance is scaled to match the ground, so you carry full speed through jumps and bhops.", default=true},
  {tab="Movement", side="Left", section="Jump & Fall", kind="Toggle", src=2622, id="mv_bhop", title="Bunny Hop", desc="Auto-jumps the instant you land (no jump cooldown). Pairs with Keep Velocity In Air to carry speed across hops.", default=false},
  {tab="Movement", side="Left", section="Jump & Fall", kind="Toggle", src=2623, id="mv_bhop_hold", title="Bhop: Hold Space", desc="Only bunny-hop while Space is held. Off = always hop.", default=true},
  {tab="Movement", side="Left", section="Jump & Fall", kind="Toggle", src=2624, id="mv_infjump", title="Infinite / Force Jump", desc="Jump again every time you press the jump key - mid-air, while crouched, or whenever the game would normally block it.", default=false},
  {tab="Movement", side="Left", section="Jump & Fall", kind="Slider", src=2625, id="jump_power", title="Jump Power", desc="Upward jump velocity (game default 25). Higher = jump higher.", default=25, min=10, max=120, rounding=0},
  {tab="Movement", side="Left", section="Jump & Fall", kind="Toggle", src=2626, id="mv_nofall", title="No Fall Penalty", desc="Caps your fall speed so every landing is as soft as a normal jump - neutralises velocity-based fall damage and stops the forced skydive/parachute on big drops. Great with high Jump Power.", default=false},
  {tab="Movement", side="Left", section="Jump & Fall", kind="Slider", src=2627, id="mv_fall_speed", title="Max Fall Speed", desc="Fastest you'll fall while No Fall Penalty is on (studs/s). Lower = softer / floatier landings.", default=25, min=8, max=90, rounding=0},
  {tab="Movement", side="Right", section="Fly", kind="Toggle", src=2631, id="mv_fly", title="Fly", desc="Free-fly via the controller's own position. WASD = move along your camera, Space = up, Ctrl / C = down. Hold nothing to hover. Flies through open air.", default=false},
  {tab="Movement", side="Right", section="Fly", kind="Slider", src=2632, id="mv_fly_speed", title="Fly Speed", desc="Studs/second while flying.", default=60, min=10, max=250, rounding=0},
  {tab="Movement", side="Right", section="Fly", kind="Paragraph", src=2633, id="fly_note", title="Heads up", content="Walk Speed and Fly are client-side velocity edits, so BHRM5's server may clamp them in a real match - test and ease off if you rubber-band. Noclip stays out (server-owned)."},
  {tab="Movement", side="Right", section="Spinbot", kind="Toggle", src=2637, id="spin_enabled", title="Spinbot", desc="Spins your replicated body so the server + other players see you whirling, while YOUR screen stays still. Doesn't touch your camera or silent aim.", default=false},
  {tab="Movement", side="Right", section="Spinbot", kind="Slider", src=2638, id="spin_speed", title="Spin Speed", desc="Radians/sec of the spin.", default=30, min=1, max=100, rounding=0},
  {tab="Movement", side="Right", section="Spinbot", kind="Toggle", src=2639, id="spin_show_local", title="Show In Third Person", desc="Spin your OWN body on your screen too (third person only) so you see exactly what the spin looks like. First person + your camera are never affected.", default=true},
  {tab="Movement", side="Right", section="Spinbot", kind="Toggle", src=2640, id="spin_aim", title="Spin Look Too", desc="Also spins your replicated look direction (head/aim), not just the body.", default=false},
  {tab="Movement", side="Right", section="Spinbot", kind="Toggle", src=2641, id="spin_lookdown", title="Pin Look Pitch", desc="Hold your replicated look at a fixed pitch (classic anti-aim 'look down').", default=false},
  {tab="Movement", side="Right", section="Spinbot", kind="Slider", src=2642, id="spin_pitch", title="Look Pitch (deg)", default=-55, min=-89, max=89, rounding=0},
  {tab="Movement", side="Right", section="Spinbot", kind="Paragraph", src=2643, id="spin_note", title="Note", content="Rewrites your 10Hz movement replication (the network hook loads at startup). Position stays real so you don't rubber-band. Silent aim is unaffected."},
  {tab="Movement", side="Right", section="Misc", kind="Toggle", src=2647, id="mv_anti_afk", title="Anti-AFK", desc="Nudges the mouse on idle to dodge the AFK kick. This one actually works (it's not Humanoid-based).", default=true},
  {tab="Debug", side="Left", section="Tools", kind="Button", src=2656, title="Remote Spy (SimpleSpy)"},
  {tab="Debug", side="Left", section="Tools", kind="Button", src=2659, title="Dex Explorer"},
  {tab="Debug", side="Left", section="Tools", kind="Button", src=2662, title="Infinite Yield"},
  {tab="Debug", side="Right", section="Utilities", kind="Button", src=2665, title="Entity / Squad Status"},
  {tab="Debug", side="Right", section="Utilities", kind="Button", src=2679, title="Module Service Status"},
  {tab="Server", side="Left", section="Server", kind="Button", src=2693, title="Rejoin Server"},
  {tab="Server", side="Left", section="Server", kind="Button", src=2694, title="Server Hop"},
  {tab="Server", side="Right", section="Info", kind="Button", src=2695, title="Copy Job Id"},
  {tab="Server", side="Right", section="Info", kind="Button", src=2699, title="Show Server Info"},
  {tab="Settings", side="Left", section="Script", kind="Button", src=2749, title="Unload Script", desc="Closes the VELCORE GUI-only menu."},
  {tab="Settings", side="Left", section="Script", kind="Paragraph", src=2750, id="tmpl_note", title="Black Hawk Rescue Mission 5", content="VELCORE GUI-only demo. Gameplay callbacks are not connected. RightShift toggles the menu."},
}